### PR TITLE
web Updated

### PR DESCRIPTION
**Pull request by minhaj-313**
add scroll bare,
convert some code to clean format
background animation
some css
etc...

### CODE REVIEW

**Comment by minhaj-313** [comment]
Please Merge My PR and please labeled it as accepted hacktoberfest. Thank You for giving me this opportunity.

**Comment by minhaj-313** [comment]
@sslabmite174  Thank You Very much.

**Comment by sslabmite174** [comment]
Star the repo pls

**Comment by minhaj-313** [comment]
Sure, If you don't mind then you can also follow me.

**Comment by sslabmite174** [comment]
> Sure, If you don't mind then you can also follow me.

done

**Pull request merged**
